import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useState } from 'react'

import { Menu, X } from 'lucide-react'

const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */

const navigation = [
  { name: 'Home', id: '/' },
  { name: 'Blog', id: '/blog' },
  { name: 'Portfolio', id: '/portfolio' },
  { name: 'Contact', id: '/contact' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [activeSection, setActiveSection] = useState('home')
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
          {/* Navigation */}
          <nav className="fixed w-full bg-slate-900/80 backdrop-blur-md z-50 border-b border-purple-500/20">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                <div className="text-2xl font-bold bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text text-transparent">
                  Maksim
                </div>

                {/* Desktop Navigation */}
                <div className="hidden md:flex space-x-8">
                  {navigation.map((item) => (
                    <Link
                      href={item.id}
                      key={item.id}
                      onClick={() => setActiveSection(item.id)}
                      className={`px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                        activeSection === item.id
                          ? 'text-purple-400'
                          : 'text-gray-300 hover:text-white'
                      }`}
                    >
                      {item.name}
                    </Link>
                  ))}
                </div>

                {/* Mobile menu button */}
                <button
                  onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                  className="md:hidden text-gray-300 hover:text-white"
                >
                  {mobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
                </button>
              </div>
            </div>

            {/* Mobile Navigation */}
            {mobileMenuOpen && (
              <div className="md:hidden bg-slate-800/95 backdrop-blur-md">
                <div className="px-2 pt-2 pb-3 space-y-1">
                  {navigation.map((item) => (
                    <Link
                      href={item.id}
                      key={item.id}
                      onClick={() => {
                        setActiveSection(item.id)
                        setMobileMenuOpen(false)
                      }}
                      className={`block w-full text-left px-3 py-2 rounded-md text-base font-medium ${
                        activeSection === item.id
                          ? 'text-purple-400 bg-slate-700'
                          : 'text-gray-300 hover:text-white hover:bg-slate-700'
                      }`}
                    >
                      {item.name}
                    </Link>
                  ))}
                </div>
              </div>
            )}
          </nav>

          {children}

          <footer className="bg-slate-900/80 backdrop-blur-md border-t border-purple-500/20 py-8">
            <div className="max-w-7xl mx-auto px-4 text-center">
              <p className="text-gray-400">© 2024 Your Name. All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
